// src/Code.svelte
<style>
    main {
        align-items: center;
        display: flex;
        flex-direction: column;
        justify-content: center;
        height: 100%;
        margin: 0;
        padding: 0;
        width: 100%;
    }

    .alphabet-canvas, .attribution-canvas, .self-attr-canvas {
        left: 0;
        position: absolute;
        transform: translateY(-150%);
        top: 0;
    }

    .code-canvas {
        /* Overridden in style='' */
        --outline-h: 100%;
        --outline-w: 100%;

        background-color: #707688;
    }

    .code-canvas.fit {
        height: var(--outline-h);
        width: var(--outline-w);
    }

    .code-canvas.aspect {
        --a: calc(1 / 1);

        height: calc(min(var(--outline-h), var(--outline-w) / var(--a)));
        width: calc(min(var(--outline-w), var(--outline-h) * var(--a)));
    }

    .progress-svg {
        --s: calc(min(120px, 200px + 15vw));

        height: var(--s);
        left: calc(50vw - var(--s) * .5);
        position: absolute;
        top: calc(50vh - var(--s) * .5);
        stroke: #fff8;
        width: var(--s);
    }

    .progress-circle {
        animation: arc-anim 1.7s ease-in-out infinite, rotation-anim 1.7s linear infinite;
        animation-delay: -.9s;
        filter: drop-shadow(0 0 calc(min(1px + .1vw, 2px)) #fff9);
        box-shadow: var(--btn-shadow);
    }

    /*
     * l = 2 * pi * 20 = 125.66
     */
    @keyframes arc-anim {
        0% {
            stroke-dashoffset: 0;
            stroke-dasharray: .5, 125.66;
        }
        50% {
            stroke-dashoffset: -18;
            stroke-dasharray: 100, 125.66;
        }
        100% {
            stroke-dashoffset: -125.66;
            stroke-dasharray: 100, 125.66;
        }
    }

    @keyframes rotation-anim {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    .round-btn {
        align-items: center;
        background: #ffffffc0;
        border-radius: 50%;
        box-shadow: var(--btn-shadow);
        color: #000d;
        display: flex;
        justify-content: center;
        height: var(--btn-size);
        position: absolute;
        transition: background-color 250ms;
        top: var(--pad-std);
        width: var(--btn-size);
    }

    .round-btn.left {
        left: var(--pad-std);
    }

    .round-btn.second-to-right {
        right: calc(var(--pad-std) * 2 + var(--btn-size));
    }

    .round-btn.right {
        right: var(--pad-std);
    }

    .round-btn:hover {
        background: #ffffffe0;
    }

    .round-btn:active {
        background: #fffffff8;
    }

</style>

<main bind:this={mainEl}>
    <canvas class='alphabet-canvas' bind:this={alphabetCanvasEl} width='2048'></canvas>
    <canvas class='attribution-canvas' bind:this={attributionCanvasEl}></canvas>
    <canvas class='self-attr-canvas' bind:this={selfAttrCanvasEl}></canvas>

    <canvas class={`code-canvas ${codeCanvasModifier}`} style={codeCanvasStyle} bind:this={codeCanvasEl}></canvas>

    <button class='round-btn left' on:click={handleImgParamsClick}>
        <Icon pic={(openDialog === 'menu') ? 'close' : 'menu'}/>
    </button>
    <button class='round-btn second-to-right' on:click={handleGenerateClick}>
        <Icon pic='reload' rotateDeg={generateRotateDeg}/>
    </button>
    <button class='round-btn right' on:click={handleDownloadClick}>
        <Icon pic={downloading ? 'pending' : 'download'}/>
    </button>

    {#if imgParams}
        <ImgParamsMenu imgParams={imgParams}
                       menuOpen={openDialog === 'menu'}
                       paramsUpdated={onParamsUpdate}
                       closeMenu={closeImgParams}
                       clickedAbout={handleAboutClick}
        />
    {/if}

    {#if progress}
        <svg class='progress-svg' viewBox='-26 -26 52 52' xmlns='http://www.w3.org/2000/svg'>
            <circle class='progress-circle' fill='none' cx='0' cy='0' r='20' stroke-width='4' xmlns='http://www.w3.org/2000/svg'/>
        </svg>
    {/if}

    {#if openDialog === 'about'}
        <About closeDialog={closeAbout}/>
    {/if}
</main>
    
<script lang='ts'>
    import { getSliderVal, ImgParams } from './model/ImgParams';
    import ImgParamsMenu from './ImgParamsMenu.svelte';
    import { onDestroy, onMount } from 'svelte';
    import Icon from './Icon.svelte';
    import { drawRandomScene, drawScene } from './draw/drawScene';
    import { setTaskExecutorListeners, submitTask, submitTaskFast } from './util/submitTask';
    import About from './About.svelte';
    import { fitViewRatio } from './model/ratios';
    import { delayToAnimationFrame } from './util/delay';
    import { dpr } from './util/dpr';

    let mainEl: HTMLElement;
    let codeCanvasEl: HTMLCanvasElement;
    let alphabetCanvasEl: HTMLCanvasElement;
    let attributionCanvasEl: HTMLCanvasElement;
    let selfAttrCanvasEl: HTMLCanvasElement;

    let progress = false;
    setTaskExecutorListeners({
        onStart: () => progress = true,
        onEnd: () => progress = false,
    });

    let imgParams: ImgParams | undefined = undefined;

    let openDialog: 'menu' | 'about' | undefined = undefined;
    function handleImgParamsClick() {
        if (openDialog === 'menu') {
            openDialog = undefined;
        } else {
            openDialog = 'menu';
        }
    }

    function closeImgParams() {
        if (openDialog === 'menu') {
            openDialog = undefined;
        }
    }

    function handleAboutClick() {
        openDialog = 'about';
    }

    function closeAbout() {
        if (openDialog === 'about') {
            openDialog = undefined;
        }
    }

    // In Safari sizes may be not ready on mount, that's why raf
    onMount(async () => {
        await setCodeCanvasWH();
        await generateScene();
    });

    let generateRotateDeg = 0;
    async function handleGenerateClick() {
        if (imgParams) {
            generateRotateDeg += 360;
            await generateScene();
        }
    }

    async function generateScene() {
        submitTaskFast(async () =>
            await drawRandomScene(
                imgParams,
                codeCanvasEl,
                alphabetCanvasEl,
                attributionCanvasEl,
                selfAttrCanvasEl,
                p => imgParams = p,
            )
        );
    }

    async function onParamsUpdate(_, updatedSize: boolean) {
        submitTask(async () => {
            if (imgParams) {
                if (updatedSize) {
                    updateCodeCanvasStyle();
                    await setCodeCanvasWH();
                }
                await drawScene(
                    imgParams,
                    codeCanvasEl,
                    alphabetCanvasEl,
                    attributionCanvasEl,
                    selfAttrCanvasEl,
                    updatedSize,
                    triggerImgParamsUpdate,
                );
            }
        });
    }

    onMount(() => window.addEventListener('resize', resizeListener));
    onDestroy(() => window.removeEventListener('resize', resizeListener));
    async function resizeListener() {
        submitTask(async () => {
            if (imgParams) {
                updateCodeCanvasStyle();
                await setCodeCanvasWH();
                await drawScene(
                    imgParams,
                    codeCanvasEl,
                    alphabetCanvasEl,
                    attributionCanvasEl,
                    selfAttrCanvasEl,
                    true,
                    triggerImgParamsUpdate,
                );
            }
        });
    }

    function triggerImgParamsUpdate() {
        imgParams = imgParams;
    }

    let codeCanvasModifier: 'fit' | 'aspect' = 'fit';
    let codeCanvasStyle: string | undefined = undefined;
    function updateCodeCanvasStyle() {
        if (imgParams) {
            const r = imgParams['output image'].ratio.val;
            codeCanvasModifier = r === fitViewRatio ? 'fit' : 'aspect';

            codeCanvasStyle = '';
            const sizeFr = getSliderVal(imgParams['output image'].size);
            if (r !== fitViewRatio || sizeFr < 1) {
                const outlineRect = mainEl.getBoundingClientRect();
                codeCanvasStyle = `--outline-h: ${outlineRect.height * sizeFr}px; --outline-w: ${outlineRect.width * sizeFr}px; `;
            }

            if (r !== fitViewRatio) {
                codeCanvasStyle += `--a: calc(${r});`;
            }
        }
    }

    async function setCodeCanvasWH() {
        await delayToAnimationFrame(); // Make sure layout happened
        const canvasRect = codeCanvasEl.getBoundingClientRect();
        codeCanvasEl.width = canvasRect.width * dpr;
        codeCanvasEl.height = canvasRect.height * dpr;
    }

    let downloading = false;
    function handleDownloadClick() {
        if (!downloading) {
            downloading = true;
            codeCanvasEl.toBlob(blob => {
                const a = document.createElement('a');
                const objUrl = URL.createObjectURL(blob);
                a.href = objUrl;
                a.download = 'CodeArt.png';
                a.click();
                setTimeout(
                    () => downloading = false,
                    1200,
                );
                setTimeout(() => URL.revokeObjectURL(objUrl), 5000);
            });
        }
    }
</script>

// app/Code.tsx
'use client'

import './Code.css'

import { About } from './About';
import { delayToAnimationFrame } from './util/delay';
import { dpr } from './util/dpr';
import { drawRandomScene, drawScene } from './draw/drawScene';
import { fitViewRatio, getFractionFromDisplayedRatio } from './model/ratios';
import { getSliderVal, ImgParams } from './model/ImgParams';
import { ImgParamsMenu } from './ImgParamsMenu';
import { Icon } from './Icon';
import { setTaskExecutorListeners, submitTask } from './util/submitTask';
import { useEffect, useRef, useState } from 'react';

export function Code() {
    const mainRef = useRef<HTMLElement>(null);
    useEffect(() => {
        function setMainSizeVars() {
            const rect = mainRef.current!.getBoundingClientRect()
            mainRef.current!.style.setProperty('--main-h', `${rect.height}px`)
            mainRef.current!.style.setProperty('--main-w', `${rect.width}px`)
        }
        setMainSizeVars()
        window.addEventListener('resize', setMainSizeVars)

        return () => window.removeEventListener('resize', setMainSizeVars)
    }, [])


    const alphabetCanvasRef = useRef<HTMLCanvasElement>(null)
    const attributionCanvasRef = useRef<HTMLCanvasElement>(null)
    const selfAttrCanvasRef = useRef<HTMLCanvasElement>(null)
    const codeCanvasRef = useRef<HTMLCanvasElement>(null)

    const [openDialog, setOpenDialog] = useState<'menu' | 'about' | undefined>(undefined);
    const [imgParams, setImgParams] = useState<ImgParams | undefined>(undefined);

    function handleImgParamsClick() {
        if (openDialog === 'menu')
            setOpenDialog(undefined)
        else
            setOpenDialog('menu')
    }

    function closeImgParams() {
        if (openDialog === 'menu')
            setOpenDialog(undefined)
    }

    function handleAboutClick() {
        setOpenDialog('about')
    }

    function closeAbout() {
        if (openDialog === 'about')
            setOpenDialog(undefined)
    }

    // In Safari sizes may be not ready on mount, that's why raf
    useEffect( () => {
        (async () => {
            await setCodeCanvasWH()
            await generateScene(true);
        })()
    }, [])

    const [generateRotateDeg, setGenerateRotateDeg] = useState(0)
    async function handleGenerateClick() {
        if (imgParams) {
            setGenerateRotateDeg(generateRotateDeg + 360)
            await generateScene()
        }
    }

    async function generateScene(initial?: boolean) {
        submitTask(async () =>
            await drawRandomScene(
                imgParams,
                codeCanvasRef.current!,
                alphabetCanvasRef.current!,
                attributionCanvasRef.current!,
                selfAttrCanvasRef.current!,
                setImgParams,
            ),
            initial,
        );
    }

    async function onParamsUpdate(_: any, updatedSize: boolean) {
        submitTask(async () => {
            if (imgParams) {
                if (updatedSize) {
                    updateCodeCanvasStyle();
                    await setCodeCanvasWH();
                }
                await drawScene(
                    imgParams,
                    codeCanvasRef.current!,
                    alphabetCanvasRef.current!,
                    attributionCanvasRef.current!,
                    selfAttrCanvasRef.current!,
                    updatedSize,
                    () => setImgParams({...imgParams}),
                );
            }
        });
    }

    useEffect(() => {
        async function drawOnResize() {
            submitTask(async () => {
                if (imgParams) {
                    updateCodeCanvasStyle()
                    await setCodeCanvasWH()
                    await drawScene(
                        imgParams,
                        codeCanvasRef.current!,
                        alphabetCanvasRef.current!,
                        attributionCanvasRef.current!,
                        selfAttrCanvasRef.current!,
                        true,
                        () => setImgParams({...imgParams}),
                    );
                }
            });
        }
        window.addEventListener('resize', drawOnResize)
        return () => window.removeEventListener('resize', drawOnResize)
    }, [imgParams])

    const [codeCanvasModifier, setCodeCanvasModifier] = useState<'fit' | 'aspect'>('fit')

    async function updateCodeCanvasStyle() {
        if (imgParams) {
            const r = imgParams['output image'].ratio.val;
            setCodeCanvasModifier(r === fitViewRatio ? 'fit' : 'aspect')

            const sizeFr = getSliderVal(imgParams['output image'].size);
            codeCanvasRef.current!.style.setProperty('--s', String(sizeFr));

            if (r !== fitViewRatio) {
                codeCanvasRef.current!.style.setProperty('--a', `calc(${getFractionFromDisplayedRatio(r)})`);
            }
        }
    }

    async function setCodeCanvasWH() {
        await delayToAnimationFrame(); // Make sure layout happened
        const canvasRect = codeCanvasRef.current!.getBoundingClientRect();
        codeCanvasRef.current!.width = canvasRect.width * dpr();
        codeCanvasRef.current!.height = canvasRect.height * dpr();
    }

    const [downloading, setDownloading] = useState(false)
    function handleDownloadClick() {
        if (!downloading) {
            setDownloading(true)
            codeCanvasRef.current!.toBlob(blob => {
                const a = document.createElement('a')
                const objUrl = URL.createObjectURL(blob!)
                a.href = objUrl
                a.download = 'CodeArt.png'
                a.click();
                setTimeout(
                    () => setDownloading(false),
                    1200,
                )
                setTimeout(() => URL.revokeObjectURL(objUrl), 5000)
            });
        }
    }

    const [progress, setProgress] = useState(false)
    useEffect(() => {
        setTaskExecutorListeners({
            onStart: () => setProgress(true),
            onEnd: () => setProgress(false),
        })
    }, [])

 
 return <main ref={mainRef}>
        <canvas className='alphabet-canvas' ref={alphabetCanvasRef} width='2048' />
        <canvas className='attribution-canvas' ref={attributionCanvasRef}/>
        <canvas className='self-attr-canvas' ref={selfAttrCanvasRef} />
        <canvas className={`code-canvas ${codeCanvasModifier}`} ref={codeCanvasRef} />

        <button className='round-btn left' onClick={handleImgParamsClick}>
            <Icon pic={(openDialog === 'menu') ? 'close' : 'menu'}/>
        </button>
        <button className='round-btn second-to-right' onClick={handleGenerateClick}>
            <Icon pic='reload' rotateDeg={generateRotateDeg}/>
        </button>
        <button className='round-btn right' onClick={handleDownloadClick}>
            <Icon pic={downloading ? 'pending' : 'download'}/>
        </button>

        {
            imgParams &&
            <ImgParamsMenu
                imgParams={imgParams}
                menuOpen={openDialog === 'menu'}
                paramsUpdated={onParamsUpdate}
                closeMenu={closeImgParams}
                clickedAbout={handleAboutClick}
            />
        }

        {
            progress &&
            <svg className='progress-svg' viewBox='-26 -26 52 52'>
                <circle className='progress-circle' fill='none' cx='0' cy='0' r='20' strokeWidth='4'/>
            </svg>
        }

        {
            openDialog === 'about'
            && <About closeDialog={closeAbout}/>
        }
    </main>
}
